<a href="https://colab.research.google.com/github/rajshreeathawale/BigData_Project/blob/main/MainProj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Main Project(BigData)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("World energy consumption.csv")
df

,country,coal_consumption,coal_electricity,coal_production,electricity_generation,fossil_fuel_consumption,gas_consumption,gas_production,oil_consumption,oil_electricity,greenhouse_gas_emissions
0,ASEAN,NaN,71.03,NaN,368.65,NaN,NaN,NaN,NaN,61.50,184.41
1,ASEAN,NaN,80.02,NaN,397.19,NaN,NaN,NaN,NaN,55.14,198.34
2,ASEAN,NaN,87.16,NaN,422.82,NaN,NaN,NaN,NaN,56.15,213.80
3,ASEAN,NaN,98.51,NaN,447.15,NaN,NaN,NaN,NaN,56.01,229.70
4,ASEAN,NaN,111.62,NaN,484.94,NaN,NaN,NaN,NaN,58.33,252.61
...,...,...,...,...,...,...,...,...,...,...,...
22007,Zimbabwe,NaN,3.69,25.105,9.19,NaN,NaN,NaN,NaN,0.04,3.27
22008,Zimbabwe,NaN,3.62,19.700,8.24,NaN,NaN,NaN,NaN,0.04,3.19
22009,Zimbabwe,NaN,3.36,20.292,7.59,NaN,NaN,NaN,NaN,0.04,2.96
22010,Zimbabwe,NaN,3.57,24.291,8.03,NaN,NaN,NaN,NaN,0.04,3.15
22011,Zimbabwe,NaN,NaN,29.554,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Handle missing values
df.fillna(0,inplace=True)

In [ ]:
df.describe()

,coal_consumption,coal_electricity,coal_production,electricity_generation,fossil_fuel_consumption,gas_consumption,gas_production,oil_consumption,oil_electricity,greenhouse_gas_emissions
count,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000,22012.000000
mean,463.034771,95.343382,726.410249,251.481867,1443.409212,350.295204,466.591996,633.968423,14.030547,69.295304
std,2746.070707,624.406507,3016.254526,1492.827826,7721.280898,1927.004343,2078.349284,3302.471007,79.727533,588.319880
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,25.152000,1.782500,0.000000,0.000000,12.472000,14.154000,0.030000,0.000000
max,44858.121000,10190.710000,48490.000000,28527.760000,137236.672000,40670.660000,40534.203000,53512.844000,1364.684000,12447.700000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22012 entries, 0 to 22011
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   country                   22012 non-null  object
 1   coal_consumption          22012 non-null  float64
 2   coal_electricity          22012 non-null  float64
 3   coal_production           22012 non-null  float64
 4   electricity_generation    22012 non-null  float64
 5   fossil_fuel_consumption   22012 non-null  float64
 6   gas_consumption           22012 non-null  float64
 7   gas_production            22012 non-null  float64
 8   oil_consumption           22012 non-null  float64
 9   oil_electricity           22012 non-null  float64
 10  greenhouse_gas_emissions  22012 non-null  float64
dtypes: float64(10), object(1)
memory usage: 1.8+ MB

In [ ]:
df.to_csv("C:\\Users\\Dell\\OneDrive\\Desktop\\World_EnergyConsumption.csv",index=False)